### PR TITLE
a place to bury treasure

### PR DESCRIPTION
**Pull request by schollz**

### CODE REVIEW

**Comment by schollz** [comment]
and added the dial

**Comment by catfact** [comment]
should be fine on norns. the only thing i'd note is that the `MP3` quark is a pretty rube goldberg kind of contraption, which does stuff like directly managing the `lame` process by its PID, and piping through a temp file:
https://github.com/supercollider-quarks/MP3/blob/master/MP3.sc#L153 

so its worth just keeping an eye on for weird bugs, and it might want a really large streaming buffer.

**Comment by catfact** [comment]
if you are going down that route anyway (leaning on unix components outside of supercollider) then i suppose one might as well get the duration by a similar method; e.g. `ffmpeg -i thing.mp3 | grep Duration` etc

**Comment by catfact** [comment]
hi ho, maybe merging this would be good!

**Comment by schollz** [comment]
>  i suppose one might as well get the duration by a similar method; e.g. `ffmpeg -i thing.mp3 | grep Duration` etc

this is a good idea, at least it will be nice for me to learn how to do that.

**Pull request merged**
